### ISSUE TITLE
Invalid mode: e164

### ISSUE THREAD

**Issue by molaeiali** [Salesflare/joi-phone-number#65]
Hey, I'm getting this error after doing:
```
import Joi = require("@hapi/joi");
const phoneJoi = Joi.extend(require('joi-phone-number'));
```
Here is my lib versions:
```    
    "joi-phone-number": "^3.1.1",
    "@hapi/joi": "^16.1.7",
```
Here is the error log:
```
$PROJECT_HOME/node_modules/@hapi/hoek/lib/error.js:23
            Error.captureStackTrace(this, exports.assert);
                  ^
Error: Invalid mode: e164
    at new module.exports ($PROJECT_HOME/node_modules/@hapi/hoek/lib/error.js:23:19)
    at module.exports ($PROJECT_HOME/node_modules/@hapi/hoek/lib/assert.js:20:11)
    at internals.Base.only ($PROJECT_HOME/node_modules/@hapi/joi/lib/base.js:201:9)
    at module.exports ($PROJECT_HOME/node_modules/joi-phone-number/lib/index.js:31:30)
    at Object.extend ($PROJECT_HOME/node_modules/@hapi/joi/lib/index.js:156:29)
    at Object.<anonymous> ($PROJECT_HOME/src/routes/joi/joi.types.ts:3:22)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Module.m._compile ($PROJECT_HOME/node_modules/ts-node/src/index.ts:493:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Object.require.extensions.<computed> [as .ts] ($PROJECT_HOME/node_modules/ts-node/src/index.ts:496:12)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> ($PROJECT_HOME/src/routes/joi/auth.joi.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
error Command failed with exit code 1.
```

**Comment by alfianwahid** [comment]
this error because you are using @hapi/joi 16.1.7 and this package still using @hapi/joi 15.x.x.

**Comment by AdriVanHoudt** [comment]
@alfianwahid thanks for triaging this. I will be looking at supporting @hapi/joi@16 momentarily

**Comment by AdriVanHoudt** [comment]
Hi @molaeiali version 4 now supports joi 16 and 17 ✨
